### PR TITLE
feat: enable timezone for cronjobs

### PR DESCRIPTION
**Pull request by ninox92**
- Subtract the localtimezone offset of the current UTC time.
- To set the timezone set: export TZ=Europe/Amsterdam

### CODE REVIEW

**Comment by jangmarker** [comment]
I think it would make sense to set the time zone by parameter to `createTask` and not by environment variable, because different tasks could be configured for different time zones.

**Comment by ninox92** [comment]
You could do that, but for the simple use-case of a cron-job it would be overkill for now.

**Comment by merencia** [comment]
Hello @ninox92 I really enjoy your solution! 

When I decide to build node-cron a follow one single premisse: do not use huge dependencies to do a simple things! So I've created tiny task scheduler in pure JavaScript, and I think your solution is exactly node-cron needs.

Thanks!

**Comment by merencia** [comment]
Timezone was added at https://github.com/merencia/node-cron/pull/101 and will be released on version 2.0.0

**Pull request closed without merging**
